config-variables:
  - GIT_USER_NAME
  - GIT_USER_EMAIL
  - HEAD_OWNER
  - UPDATE_ACTIONS_BRANCH
  - UPDATE_ACTIONS_COOLDOWN
  - UPDATE_ACTIONS_DAILY
  - UPDATE_DEPENDENCIES_BRANCH
  - UPDATE_DEPENDENCIES_DAILY
  - UPDATE_USER_AGENT_BRANCH
  - UPDATE_USER_AGENT_MONTHLY
