name: Update dependencies
on:
  schedule:
    - cron: '17 17 * * 2,4,6'
  workflow_dispatch:

permissions: {}

concurrency:
  group: update-dependencies
  cancel-in-progress: false

jobs:
  output_variables:
    name: Output variables
    if: github.event_name != 'schedule' || vars.UPDATE_DEPENDENCIES_CRON
    runs-on: ubuntu-latest
    outputs:
      default_head_branch: ${{ steps.variables.outputs.default_head_branch }}
      default_head_owner: ${{ steps.variables.outputs.default_head_owner }}
      matrix: ${{ steps.variables.outputs.matrix }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.14"

      - name: Output variables
        id: variables
        run: python -m bot tools variables dependencies

  update_dependencies:
    name: Update dependencies (${{ matrix.repo }})
    needs: [output_variables]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.output_variables.outputs.matrix) }}
    env:
      HEAD_BRANCH: ${{ vars.UPDATE_DEPENDENCIES_BRANCH || needs.output_variables.outputs.default_head_branch }}
      HEAD_OWNER: ${{ vars.HEAD_OWNER || needs.output_variables.outputs.default_head_owner }}

    steps:
      - name: Checkout bot repo (${{ github.repository }})
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          path: dlp-bot
          persist-credentials: false

      - name: Checkout working repo (${{ format('{0}/{1}', env.HEAD_OWNER, matrix.repo) }})
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: ${{ format('{0}/{1}', env.HEAD_OWNER, matrix.repo) }}
          path: ${{ matrix.repo }}
          fetch-depth: 0
          persist-credentials: true  # Needed to git-push
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure git user
        env:
          GIT_USER_NAME: ${{ vars.GIT_USER_NAME || 'dlp-bot' }}
          GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL || 'bot@yt-dlp.org' }}
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.14"

      - name: Install Python requirements
        run: |
          python -m pip install -U --require-hashes -r "dlp-bot/requirements/pip.txt"
          python -m pip install -U --require-hashes -r "dlp-bot/requirements/update-dependencies.txt"

      - name: Install pnpm
        if: matrix.repo == 'ejs'
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320  # v5.0.0
        with:
          version: "10"

      - name: Install Node
        if: matrix.repo == 'ejs'
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f  # v6.3.0
        with:
          # minimum supported version
          node-version: "20.0"

      - name: Install Bun
        if: matrix.repo == 'ejs'
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6  # v2.2.0
        with:
          # need bun 1.2+ for migrating package-lock.json to bun.lock
          bun-version: "1.2"
          no-cache: true

      - name: Install Deno
        if: matrix.repo == 'ejs'
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb  # v2.0.3
        with:
          # minimum supported version
          deno-version: "2.0.0"

      - name: Run bot update dependencies ${{ matrix.repo }}
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          WORKING_REPO: ${{ matrix.repo }}
        run: |
          cd dlp-bot
          python -m bot update dependencies \
            --pr \
            --verbose \
            --git-protocol https \
            --head "${HEAD_OWNER}:${HEAD_BRANCH}" \
            -- \
            "${WORKING_REPO}" ../"${WORKING_REPO}"
