name: Update actions
on:
  schedule:
    - cron: '17 17 * * 1,3,5'
  workflow_dispatch:

permissions: {}

concurrency:
  group: update-actions
  cancel-in-progress: false

jobs:
  output_variables:
    name: Output variables
    if: github.event_name != 'schedule' || vars.UPDATE_ACTIONS_CRON
    runs-on: ubuntu-latest
    outputs:
      default_head_branch: ${{ steps.variables.outputs.default_head_branch }}
      default_head_owner: ${{ steps.variables.outputs.default_head_owner }}
      matrix: ${{ steps.variables.outputs.matrix }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: "3.14"

      - name: Output variables
        id: variables
        run: python -m bot tools variables actions

  update_actions:
    name: Update actions (${{ matrix.repo }})
    needs: [output_variables]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.output_variables.outputs.matrix) }}
    env:
      HEAD_BRANCH: ${{ vars.UPDATE_ACTIONS_BRANCH || needs.output_variables.outputs.default_head_branch }}
      HEAD_OWNER: ${{ vars.HEAD_OWNER || needs.output_variables.outputs.default_head_owner }}

    steps:
      - name: Checkout bot repo (${{ github.repository }})
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          path: dlp-bot
          persist-credentials: false

      - name: Checkout working repo (${{ format('{0}/{1}', env.HEAD_OWNER, matrix.repo) }})
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          repository: ${{ format('{0}/{1}', env.HEAD_OWNER, matrix.repo) }}
          path: ${{ matrix.repo }}
          fetch-depth: 0
          persist-credentials: true  # Needed to git-push
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure git user
        env:
          GIT_USER_NAME: ${{ vars.GIT_USER_NAME || 'dlp-bot' }}
          GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL || 'bot@yt-dlp.org' }}
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"

      - name: Configure SSH signing key
        if: ${{ vars.SSH_SIGNING_KEY_ID }}
        env:
          SSH_AUTH_SOCK: /tmp/ssh-auth-sock-${{ github.run_id }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_SIGNING_KEY_ID: ${{ vars.SSH_SIGNING_KEY_ID }}
        run: |
          ssh-agent -a "${SSH_AUTH_SOCK}"
          printf -- '%s\n' "${SSH_PRIVATE_KEY}" | ssh-add -
          git config --global user.signingkey "${SSH_SIGNING_KEY_ID}"
          git config --global gpg.format ssh
          git config --global commit.gpgsign true

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: "3.14"

      - name: Install requirements
        run: |
          python -m pip install -U --require-hashes -r "dlp-bot/requirements/pip.txt"
          python -m pip install -U --require-hashes -r "dlp-bot/requirements/update.txt"

      - name: Run bot update actions ${{ matrix.repo }}
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          SSH_AUTH_SOCK: /tmp/ssh-auth-sock-${{ github.run_id }}
          WORKING_REPO: ${{ matrix.repo }}
          COOLDOWN: ${{ vars.UPDATE_ACTIONS_COOLDOWN }}
          REBASE_PR: ${{ (vars.UPDATE_ACTIONS_REBASE && '1') || '0' }}
          OVERWRITE_PR: ${{ (vars.UPDATE_ACTIONS_OVERWRITE && '1') || '0' }}
          UPDATE_PR_COMMAND_PREFIX: ${{ vars.UPDATE_PR_COMMAND_PREFIX || '@dlp-bot' }}
          UPDATE_PR_COMMAND_ALLOWLIST: ${{ vars.UPDATE_PR_COMMAND_ALLOWLIST || '@yt-dlp/core' }}
        run: |
          cd dlp-bot
          optional_args=()
          if (( REBASE_PR )); then
            optional_args+=(--rebase-pr)
          fi
          if (( OVERWRITE_PR )); then
            optional_args+=(--overwrite-pr)
          fi
          python -m bot update actions \
            --pr \
            --verbose \
            --git-protocol https \
            --head "${HEAD_OWNER}:${HEAD_BRANCH}" \
            --exclude-newer "${COOLDOWN}" \
            --pr-command-prefix "${UPDATE_PR_COMMAND_PREFIX}" \
            --pr-command-allowlist "${UPDATE_PR_COMMAND_ALLOWLIST}" \
            "${optional_args[@]}" \
            -- \
            "${WORKING_REPO}" ../"${WORKING_REPO}"
